name: validators
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: 3.10.1

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.6.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
