include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    prefer_const_constructors: true
    avoid_relative_lib_imports: true
    avoid_print: true
    avoid_redundant_argument_values: true
    cancel_subscriptions: true
    exclude:
      - lib/**.g.dart
      - lib/**.freezed.dart
analyzer:
  plugins:
    - custom_lint
