name: meddly
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  animate_do: ^3.0.2
  appointment:
    path: packages/appointment
  authentication:
    path: packages/authentication
  calendar:
    path: packages/calendar
  dartz: ^0.10.1
  dio: ^5.0.3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.2
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  go_router: ^6.5.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.5
  intl: ^0.17.0
  measurement:
    path: packages/measurement
  medicine:
    path: packages/medicine
  notifications:
    path: packages/notifications
  pin_code_fields: ^7.4.0
  predictions:
    path: packages/predictions
  riverpod_annotation: ^2.1.0
  user:
    path: packages/user
  validators:
    path: packages/validators

dev_dependencies:
  build_runner: ^2.3.0
  custom_lint: ^0.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  riverpod_generator: ^2.2.0
  riverpod_lint: ^1.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
