name: meddly
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: 3.10.1

dependencies:
  animate_do: ^3.0.2
  appointment:
    path: packages/appointment
  calendar:
    path: packages/calendar
  dio: ^5.1.2
  equatable: ^2.0.5
  export:
    path: packages/export
  firebase_auth_repository:
    git:
      url: git@github.com:lorensala/firebase_auth_repository.git
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.6
  flutter_local_notifications: ^14.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  mask_text_input_formatter: ^2.4.0
  measurement:
    path: packages/measurement
  medicine:
    path: packages/medicine
  notifications:
    path: packages/notifications
  open_file_plus: ^3.4.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  predictions:
    path: packages/predictions
  riverpod_annotation: ^2.1.1
  share_plus: ^7.0.2
  supervisor:
    path: packages/supervisor
  user:
    path: packages/user
  validators:
    path: packages/validators

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
