name: meddly
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  animate_do: ^3.0.2
  authentication:
    path: packages/authentication
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  calendar:
    path: packages/calendar
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.2.0
  hydrated_bloc: ^9.0.0
  intl: ^0.17.0
  notifications:
    path: packages/notifications
  pin_code_fields: ^7.4.0
  predictions:
    path: packages/predictions
  riverpod_annotation: ^1.2.1
  user:
    path: packages/user
  validators:
    path: packages/validators

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  riverpod_generator: ^1.1.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/

  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic
        - asset: assets/fonts/BeVietnamPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/BeVietnamPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/BeVietnamPro-ThinItalic.ttf
          weight: 100
          style: italic
