name: meddly
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: 3.10.1

dependencies:
  animate_do: ^3.0.2
  appointment:
    path: packages/appointment
  calendar:
    path: packages/calendar
  dio: ^5.1.2
  equatable: ^2.0.5
  export:
    path: packages/export
  firebase_auth_repository:
    git:
      url: git@github.com:lorensala/firebase_auth_repository.git
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  measurement:
    path: packages/measurement
  medicine:
    path: packages/medicine
  notifications:
    path: packages/notifications
  open_file_plus: ^3.4.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  predictions:
    path: packages/predictions
  riverpod_annotation: ^2.1.1
  user:
    path: packages/user
  validators:
    path: packages/validators

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/svg/

  fonts:
    - family: Be Vietnam Pro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
          style: italic
        - asset: assets/fonts/BeVietnamPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/BeVietnamPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/BeVietnamPro-ThinItalic.ttf
          weight: 100
          style: italic

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/assets/fonts/Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets/assets/fonts/Poppins-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets/assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/assets/fonts/Poppins-LightItalic.ttf
  #         weight: 300
  #         style: italic
  #       - asset: assets/assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/assets/fonts/Poppins-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/assets/fonts/Poppins-SemiBoldItalic.ttf
  #         weight: 600
  #         style: italic
  #       - asset: assets/assets/fonts/Poppins-Thin.ttf
  #         weight: 100
  #       - asset: assets/assets/fonts/Poppins-ThinItalic.ttf
  #         weight: 100
  #         style: italic
