// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcIwhcdU-mnBGWxBNG0-6TXAG1QFW8Ig',
    appId: '1:238329653617:android:14a7611aeebada80ffaed0',
    messagingSenderId: '238329653617',
    projectId: 'meddly-fbcf7',
    storageBucket: 'meddly-fbcf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfFd3iQR-qfLhQVrD6B1X8cJVT4InxmoQ',
    appId: '1:238329653617:ios:51e68ad91212748cffaed0',
    messagingSenderId: '238329653617',
    projectId: 'meddly-fbcf7',
    storageBucket: 'meddly-fbcf7.appspot.com',
    androidClientId:
        '238329653617-utlm1603lrsphunmgkr0t5cjjfuej55p.apps.googleusercontent.com',
    iosClientId:
        '238329653617-5or36b58qumk1tmjme0qa30h59gn2981.apps.googleusercontent.com',
    iosBundleId: 'com.lorenzosala.meddly',
  );
}
