name: notifications
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: 3.10.1

dependencies:
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  json_annotation: ^4.8.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1
