name: calendar
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  json_annotation: ^4.8.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
